/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication3;

import dao.Config;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class credit extends javax.swing.JFrame {
    Connection con ;
    ResultSet rs;
    Statement st;
    Config c = new Config();
    dao.connection cn=new dao.connection();

    /**
     * Creates new form credit
     */
    public credit() {
    cn.openDb();
         try
        {
            Class.forName(c.driver);
             con=DriverManager.getConnection(c.url);
             con.setAutoCommit(true);
        }
        catch(Exception ee)
        {
        
            System.out.println(ee);
        }
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        
        
        initComponents();
    
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int) tk.getScreenSize().getWidth();
        int ysize=(int) tk.getScreenSize().getHeight();
        
this.setSize(xsize, ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        snametxt = new javax.swing.JTextField();
        amounttxt = new javax.swing.JTextField();
        datetxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Shop Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 210, 112, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Amount");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 290, 112, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 370, 112, 30);

        snametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        snametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snametxtActionPerformed(evt);
            }
        });
        getContentPane().add(snametxt);
        snametxt.setBounds(680, 210, 140, 40);

        amounttxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amounttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amounttxtActionPerformed(evt);
            }
        });
        getContentPane().add(amounttxt);
        amounttxt.setBounds(680, 290, 140, 40);

        datetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetxtActionPerformed(evt);
            }
        });
        getContentPane().add(datetxt);
        datetxt.setBounds(680, 370, 140, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/Credit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 470, 100, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/Reset.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 470, 100, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/Back.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(800, 470, 100, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/PicsArt_05-05-03.13.00-6830x3840-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void snametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snametxtActionPerformed

    private void amounttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amounttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amounttxtActionPerformed

    private void datetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(snametxt.getText().equals("") || amounttxt.getText().equals("") || datetxt.getText().equals(""))
            {
                   JOptionPane.showMessageDialog(null, "Please Fill All Details");
                   
                   snametxt.setText("");
                   amounttxt.setText("");
                   datetxt.setText("");
            }
           else
            {
                    rs=cn.selectQuery("select * from balanceheet where shop_name='"+snametxt.getText()+"'");
                  int oldamount=0;
                  rs.first(); 
                  oldamount=rs.getInt("amount");
                 
                  int credit=Integer.parseInt(amounttxt.getText()); 
                  if(oldamount < credit)             
                  {
                      JOptionPane.showMessageDialog(null, "Please Enter Valid Amount");
                        snametxt.setText(null);
       amounttxt.setText(null);
       datetxt.setText(null);
                  }
                  else
                  {
                      
                      int newamount=oldamount - credit ;
                      cn.exMyQuery("update balanceheet set amount="+newamount+" where shop_name='"+snametxt.getText()+"'; insert into creditdetail(shop_name,amount,c_date) values('"+snametxt.getText()+"',"+Integer.parseInt(amounttxt.getText())+",'"+datetxt.getText()+"')");

                       JOptionPane.showMessageDialog(null, "Money Credited Rs -> "+amounttxt.getText()+"");
        //              cn.exMyQuery("insert into creditdetail(shop_name,amount,c_date) values('"+snametxt.getText()+"',"+Integer.parseInt(amounttxt.getText())+",'"+datetxt.getText()+"')");                  
                   snametxt.setText(null);
       amounttxt.setText(null);
       datetxt.setText(null);
                  }
             
        
            }
                 
             
        } catch (SQLException ex) {
            Logger.getLogger(credit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       snametxt.setText(null);
       amounttxt.setText(null);
       datetxt.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new main_frm().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new credit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amounttxt;
    private javax.swing.JTextField datetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField snametxt;
    // End of variables declaration//GEN-END:variables
}
