/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication3;

import dao.Config;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author lenovo
 */
public class purchase extends javax.swing.JFrame {
Connection con ;
    ResultSet rs;
    Statement st;
    Config c = new Config();
   dao.connection cn=new dao.connection();
    /**
     * Creates new form purchase
     */
    public purchase() {
    cn.openDb();
         try
        {
            Class.forName(c.driver);
             con=DriverManager.getConnection(c.url);
            
        }
        catch(Exception ee)
        {
        
            System.out.println(ee);
        }
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        
        
        initComponents();
    
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int) tk.getScreenSize().getWidth();
        int ysize=(int) tk.getScreenSize().getHeight();
        
this.setSize(xsize, ysize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnametxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        datetxt = new javax.swing.JTextField();
        quantitytxt = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 510, 100, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 420, 100, 32);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Product Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 270, 100, 32);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Price");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 330, 100, 32);

        pnametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(pnametxt);
        pnametxt.setBounds(660, 270, 140, 40);

        pricetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(pricetxt);
        pricetxt.setBounds(660, 340, 140, 40);

        datetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(datetxt);
        datetxt.setBounds(660, 480, 140, 40);

        quantitytxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(quantitytxt);
        quantitytxt.setBounds(660, 410, 140, 40);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/Reset.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(650, 630, 100, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/Back.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(800, 630, 100, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/purchase.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(490, 630, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/PicsArt_05-05-03.13.00-6830x3840-1366x768.jpg"))); // NOI18N
        jLabel1.setText("Purchase Id");
        jLabel1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        datetxt.setText(null);
        pnametxt.setText(null);
        pricetxt.setText(null);
        quantitytxt.setText(null);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new main_frm().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    try {
        if(pnametxt.getText().equals("") || pricetxt.getText().equals("") || quantitytxt.getText().equals("")|| datetxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Fill All Details");
        }
        else
        {
            
        
        rs=cn.selectQuery("select * from stock where product_name='"+pnametxt.getText()+"'");
        if(!rs.next())
        {
            int n = JOptionPane.showConfirmDialog(
            null,
            "Would You Like To Add New Product",
            "Product Is Not Available",
            JOptionPane.YES_NO_OPTION);

        if(true){ 
          String s2=  cn.exMyQuery("insert into stock(product_name,quantity) values('"+pnametxt.getText()+"',"+Integer.parseInt(quantitytxt.getText())+"); insert into purchase(product_name,price,quantity,p_date) values('"+pnametxt.getText()+"',"+Integer.parseInt(pricetxt.getText())+","+Integer.parseInt(quantitytxt.getText())+",'"+datetxt.getText()+"')");
         cn.exMyQuery(s2);
          datetxt.setText(null);
        pnametxt.setText(null);
        pricetxt.setText(null);
        quantitytxt.setText(null);
       JOptionPane.showMessageDialog(null, "Product Is Added And Purchased");
        }
        else 
        {
           JOptionPane.showMessageDialog(null, "Product Will Not Be Purchased");
        datetxt.setText(null);
        pnametxt.setText(null);
        pricetxt.setText(null);
        quantitytxt.setText(null);
    
        }
        }
        else
        {
           
            rs=cn.selectQuery("select * from stock where product_name='"+pnametxt.getText()+"'");
            rs.first();
            int oldqnty=rs.getInt("quantity");
            int purchase=Integer.parseInt(quantitytxt.getText());
            int newqnty=oldqnty + purchase ;
            
              String s2="insert into purchase(product_name,price,quantity,p_date) values('"+pnametxt.getText()+"',"+Integer.parseInt(pricetxt.getText())+","+Integer.parseInt(quantitytxt.getText())+",'"+datetxt.getText()+"') ; update stock set quantity="+newqnty+" where product_name='"+pnametxt.getText()+"'";
             cn.exMyQuery(s2);
              JOptionPane.showMessageDialog(null, "Successfully Purchased ");
            
        
        datetxt.setText(null);
        pnametxt.setText(null);
        pricetxt.setText(null);
        quantitytxt.setText(null);

        }
        }
    } catch (SQLException ex) {
        Logger.getLogger(purchase.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datetxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField pnametxt;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JTextField quantitytxt;
    // End of variables declaration//GEN-END:variables
}
